networkId: N9DU6hLkTAbvcpji3TCKPPd3UQWKGyzUxGmgJEyvhByqAjfD
nodes:
  - peerId: 12D3KooWN6Wwdod3axHpfWq1anBCgYG1sZK42RpgEZEokT4KnMu7
    addresses:
      - stage1-any-sync-node1.toolpad.org:443
      - stage1-any-sync-node1.toolpad.org:1443
      - quic://stage1-any-sync-node1.toolpad.org:5430
    types:
      - tree
  - peerId: 12D3KooWJuqyFQ2ZgnYFNhdHAddF7DrTPP2rNueLjw5BWDJa9kqg
    addresses:
      - stage1-any-sync-node2.toolpad.org:443
      - stage1-any-sync-node2.toolpad.org:1443
      - quic://stage1-any-sync-node2.toolpad.org:5430
    types:
      - tree
  - peerId: 12D3KooWCub3vY3kWmAQ5qf9TtKBHKY6Yk7F6tGb13M1sXqvcbV4
    addresses:
      - stage1-any-sync-node3.toolpad.org:443
      - stage1-any-sync-node3.toolpad.org:1443
      - quic://stage1-any-sync-node3.toolpad.org:5430
    types:
      - tree
  - peerId: 12D3KooWRzT7eeiqPpkaXabqrtLEi1WmWPoUqZVRYiguUdJQz3sz
    addresses:
      - stage1-any-sync-node4.toolpad.org:443
      - stage1-any-sync-node4.toolpad.org:1443
      - quic://stage1-any-sync-node4.toolpad.org:5430
    types:
      - tree
  - peerId: 12D3KooWPkZDAzAzioUmtd2HkPeFb8mrMgkkYtfL5Es69dbhoUMT
    addresses:
      - stage1-any-sync-node5.toolpad.org:443
      - stage1-any-sync-node5.toolpad.org:1443
      - quic://stage1-any-sync-node5.toolpad.org:5430
    types:
      - tree
  - peerId: 12D3KooWF5pVsv8oaPeZj7MeAXQAbdqqrGB7AEENMnxguZtEi44V
    addresses:
      - stage1-any-sync-node6.toolpad.org:443
      - stage1-any-sync-node6.toolpad.org:1443
      - quic://stage1-any-sync-node6.toolpad.org:5430
    types:
      - tree
  - peerId: 12D3KooW9xRUDQbW6bbsek45dQop9BDZBC8ATCpKxYssE8zMy2wa
    addresses:
      - stage1-any-sync-node7.toolpad.org:443
      - stage1-any-sync-node7.toolpad.org:1443
      - quic://stage1-any-sync-node7.toolpad.org:5430
    types:
      - tree
  - peerId: 12D3KooWBqUE5e6BuxWDiAAvYATq36qCUvNysyDMdddUqmeCb5jG
    addresses:
      - stage1-any-sync-node8.toolpad.org:443
      - stage1-any-sync-node8.toolpad.org:1443
      - quic://stage1-any-sync-node8.toolpad.org:5430
    types:
      - tree
  - peerId: 12D3KooWKcGtB8jsW7mpB8zWMdVrPTZygnwkRoUKBd2ETmRDFa8x
    addresses:
      - stage1-any-sync-filenode3.toolpad.org:443
      - stage1-any-sync-filenode3.toolpad.org:1443
      - quic://stage1-any-sync-filenode3.toolpad.org:5430
    types:
      - file
  - peerId: 12D3KooWR5ishjnaTfLbwQur6ifXSQDLSroaQxWH1KHmR1YL9Srk
    addresses:
      - stage1-any-sync-filenode2.toolpad.org:443
      - stage1-any-sync-filenode2.toolpad.org:1443
      - quic://stage1-any-sync-filenode2.toolpad.org:5430
    types:
      - file
  - peerId: 12D3KooWAzNCQWQSdfspUCT6ea3TLvJFahEHwXndh8PQGanjHhbF
    addresses:
      - stage1-any-sync-filenode1.toolpad.org:443
      - stage1-any-sync-filenode1.toolpad.org:1443
      - quic://stage1-any-sync-filenode1.toolpad.org:5430
    types:
      - file
  - peerId: 12D3KooWHyWNKYPdYeFK9eQ32UK9uqM1yTdXZT6qTTbtCowCYBAp
    addresses:
      - stage1-any-sync-coordinator2.toolpad.org:443
      - stage1-any-sync-coordinator2.toolpad.org:1443
      - quic://stage1-any-sync-coordinator2.toolpad.org:5430
    types:
      - coordinator
  - peerId: 12D3KooWNPpzKPUzcf86KemKwa3ap8kBfCmPRWkBsvymGZdoBdni
    addresses:
      - stage1-any-sync-coordinator1.toolpad.org:443
      - stage1-any-sync-coordinator1.toolpad.org:1443
      - quic://stage1-any-sync-coordinator1.toolpad.org:5430
    types:
      - coordinator
  - peerId: 12D3KooWB4hmEo7YAdWzAaFpjyk4npkcwrPm2kRigsWu3MP9Xdmg
    addresses:
      - stage1-any-sync-coordinator3.toolpad.org:443
      - stage1-any-sync-coordinator3.toolpad.org:1443
      - quic://stage1-any-sync-coordinator3.toolpad.org:5430
    types:
      - coordinator
  - peerId: 12D3KooWCCe34B5jMauqR8hQzm8XWwndrk8a3exsee93SWUe59TH
    addresses:
      - stage1-any-sync-consensusnode1.toolpad.org:443
      - stage1-any-sync-consensusnode1.toolpad.org:1443
      - quic://stage1-any-sync-consensusnode1.toolpad.org:5430
    types:
      - consensus
  - peerId: 12D3KooWMmkxdAJa51wTVNLdkSTooRq6wZhdig4AjgKbuNFQJehD
    addresses:
      - stage1-any-sync-consensusnode2.toolpad.org:443
      - stage1-any-sync-consensusnode2.toolpad.org:1443
      - quic://stage1-any-sync-consensusnode2.toolpad.org:5430
    types:
      - consensus
  - peerId: 12D3KooWCqqbJ6iLNr9cpbZ76h3aSbStxV25QdxwxpUeRKjHAaBx
    addresses:
      - stage1-any-sync-consensusnode3.toolpad.org:443
      - stage1-any-sync-consensusnode3.toolpad.org:1443
      - quic://stage1-any-sync-consensusnode3.toolpad.org:5430
    types:
      - consensus